//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Receipt
{
    public string Customer;
    public int IDnum;
    public Item[] ItemsBought;

    public Receipt(string name, int id, Item[] b)
    {
        Customer = name;
        IDnum = id;
        ItemsBought = b;
    }
}

