//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReceiptDataBase
{
    public Receipt[] ReceiptBook = new Receipt[30];
    private int index = 0;
    public void addReceipt(Receipt r)
    {
        ReceiptBook[index] = r;
        index++;
    }
}

