//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Generate Checks Controller : IGenerateRebate
{
	public virtual Rebate DB Rebate DB
	{
		get;
		set;
	}

	public virtual Observer Observer
	{
		get;
		set;
	}

	public virtual string GenerateChecks(object percent, object Date)
	{
		throw new System.NotImplementedException();
	}

}

