//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product
{
	private string name
	{
		get;
		set;
	}

	private double price
	{
		get;
		set;
	}

	private int ID
	{
		get;
		set;
	}

	public virtual string GetName()
	{
		throw new System.NotImplementedException();
	}

	public virtual double GetPrice()
	{
		throw new System.NotImplementedException();
	}

	public virtual int SetQuantity()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetQuantity()
	{
		throw new System.NotImplementedException();
	}

}

