//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product DB
{
	public virtual List<Tuple<product, int>> inventory
	{
		get;
		set;
	}

	public virtual Product Product
	{
		get;
		set;
	}

	public virtual product FindItem(int Product_ID)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<products> GetProductList(object TUple<int, object int>)
	{
		throw new System.NotImplementedException();
	}

}

