//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Transaction DB
{
	private List<Receipt> receipts
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual void AddTransaction(object Receipt)
	{
		throw new System.NotImplementedException();
	}

	public virtual Transaction GetTransaction(object ID)
	{
		throw new System.NotImplementedException();
	}

}

