//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Input Form
{
	public virtual ISubmitRebate rebate
	{
		get;
		set;
	}

	public virtual IReturnItem return
	{
		get;
		set;
	}

	public virtual ICreateTransaction transaction
	{
		get;
		set;
	}

	public virtual IRebateCheck IRebateCheck
	{
		get;
		set;
	}

	public virtual State State
	{
		get;
		set;
	}

	public virtual void PocessReturn(object int, object List<Tuple<int, object int>>)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GenerateChecks(object double, object GeTimeClock)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddToRebateList(object GetTimeClock, object double, object int)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateTransaction(object List<Tuple<int, object int>>)
	{
		throw new System.NotImplementedException();
	}

}

