//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Output Form : Observer
{
	public virtual State State
	{
		get;
		set;
	}

	public virtual void Menu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update(object string)
	{
		throw new System.NotImplementedException();
	}

}

