//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product
{
    private string _name; //The name of the product
    private int _ID; //Product's ID number
    private double _price; //Prduct's Price represented as a double ($XX.xx)
    private int _quantity;


    /// <summary>
    /// Getter for the _name field
    /// </summary>
	private string Name
	{
        get
        {
            return _name;
        }
	}

    /// <summary>
    /// Getter for the _price field
    /// </summary>
	private double Price
	{
        get
        {
            return _price;
        }
	}

    /// <summary>
    /// Getter for _ID field
    /// </summary>
	private int ID
	{
        get
        {
            return _ID;
        }
	}

    /// <summary>
    /// Getter/Setter of _quantity field
    /// </summary>
    private int Quantity
    {
        get
        {
            return _quantity;
        }
        set
        {
            _quantity = Quantity;
        }
    }























	public virtual string GetName()
	{
		throw new System.NotImplementedException();
	}

	public virtual double GetPrice()
	{
		throw new System.NotImplementedException();
	}

	public virtual int SetQuantity()
	{
		throw new System.NotImplementedException();
	}

	public virtual int GetQuantity()
	{
		throw new System.NotImplementedException();
	}

}

