//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rebate DB
{
	public virtual string AddRebateToList(object Rebate)
	{
		throw new System.NotImplementedException();
	}

	public virtual double GenerateRebateCost(object double)
	{
		throw new System.NotImplementedException();
	}

}

