//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rebate Controller : ISubmitRebate
{
	public virtual Observer Observer
	{
		get;
		set;
	}

	public virtual Transaction DB Transaction DB
	{
		get;
		set;
	}

	public virtual string AddToRebateList(object GetTimeClock, object double, object int)
	{
		throw new System.NotImplementedException();
	}

}

