//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Transaction
{
	private GetTimeClock date
	{
		get;
		set;
	}

	private int sales_ID
	{
		get;
		set;
	}

	private List<Tuple<product, int>> items
	{
		get;
		set;
	}

	public virtual Model Model
	{
		get;
		set;
	}

	public virtual Cart Cart
	{
		get;
		set;
	}

	public virtual void CreateTransaction(object sales_ID, object List<Tuple<Product, object quantity>>)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveItem(object Transaction, object List<int, string int>)
	{
		throw new System.NotImplementedException();
	}

}

