//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Purchase
{
   
    private List<string> _itemChoice;
    private List<double> _itemPrice;
    private string _month;
    public double total;

    //Constructor
    public Purchase(List<string> item, List<double> price, string month)
    {
        _itemChoice = item;
        _itemPrice = price;
        _month = month;
    }

    public List<string> getItem
    {
        get
        {
            return _itemChoice;
        }
    }

    public List<double> getPrice
    {
        get
        {
            return _itemPrice;
        }
    }

    public string getMonth
    {
        get
        {
            return _month;
        }
    }

    public void checkOut()
    {
        string choice;
        

        Console.WriteLine("What would you like to purchase? ");
        _itemChoice.Add(Console.ReadLine());
        Console.WriteLine("What is the price? ");
        _itemPrice.Add(Convert.ToInt32(Console.ReadLine()));

        Console.WriteLine("Do you wish to enter another item? (Y)es or (N)o");
        choice = Console.ReadLine().ToUpper();

    }//end checkout

    public double calcTotal(List<double> prices)
    {
        foreach(double a in prices)
        {
            total += a;
        }
        return total;
    }

}

