//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rebate
{
	public virtual void calculateRebate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void isGood()
	{
		throw new System.NotImplementedException();
	}
    //Sends receipt 
	public virtual void isValid()
	{
		throw new System.NotImplementedException();
	}

}

