//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Return
{
    
    /*
    Console.WriteLine("Please enter receipt number: ");
                        recNum = Convert.ToInt32(Console.ReadLine());
                        if (!ValidChecks.ContainsValue(recNum))
                        {
                            Console.WriteLine("Invalid Receipt Number");
                            return;
                        }//End if not in dictionary
                        else
                        {
                            //Display receipt so user knows what it contains

                            //Ask user which item they would like to return
                            Console.WriteLine("Which Item would you like to return?: ");
                            itemReturn = Console.ReadLine();

                            //Ask quantity of item being returned
                            Console.WriteLine("How many do you need to return?: ");
                            itemQuantReturn = Convert.ToInt32(Console.ReadLine());
                            //call return

                        }//end else in dictionary
    */


    //Search receipt to verify item it in receipt
    //Delete item from receipt
    //Create new receipt
    //Add old receipt to InvalidChecks

}

