//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
namespace ConsoleApplication1
{
    public static class Clock
    {



        private static int Day { get; set; }
        private static int Month { get; set; }
        private static int Year { get; set; }

        public static string ClockToString()
        {

            string s = (Month + "/" + Day + "/" + Year);
            return s;
        }
        public static string CheckTime()
        {
            StringBuilder newDate = new StringBuilder();
            bool repeat2 = true;
            while (repeat2)
            {

                Console.WriteLine("Is this the correct date " + ClockToString() + " (y/n)");
                char[] yn = (Console.ReadLine().ToUpper()).ToCharArray();
                switch (yn[0])
                {
                    case 'Y':
                        {
                            return ClockToString();
                            //repeat2 = false;
                            //break;
                        }
                    case 'N':
                        {
                            Console.WriteLine("Enter month: ");
                            newDate.Append(Console.ReadLine());
                            Console.WriteLine("Enter day: ");
                            newDate.Append(Console.ReadLine());
                            Console.WriteLine("Enter year: ");
                            newDate.Append(Console.ReadLine());
                            return newDate.ToString();
                        }
                    default:
                        {
                            throw new IOException("non valid input\n");
                            //  Console.WriteLine("Non valid input\n");
                            // break;
                        }
                }
            }
            return ClockToString();
        }

    }

}
