//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace ConsoleApplication1
{
    public class Item
    {
        private int _numOf;
        private double _value;
        private double _totalVal;
        public int numOf { get { return _numOf; } }
        public double value { get { return _value; } }
        public double totalVal { get { return _totalVal; } }

        public void reset()
        {
            this._numOf = 0;
            this._totalVal = 0;
        }
        public Item(int num, double val, double tot)
        {
            this._numOf = num;
            this._value = val;
            this._totalVal = tot;
        }

        public void add(int num)
        {
            if (num > 0)
            {
                this._numOf += num;
                this._totalVal += (num * value);
            }

        }
        public void remove(int num)
        {
            if (num > 0 && num < numOf)
            {
                this._numOf -= num;
                this._totalVal -= num * totalVal;
            }

        }
    }
}

