//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace ConsoleApplication1
{
        public class ItemDatabase
        {
            
            private Item[] Inventory;
            private double _totalcost;
            public double totalCost{ get{return _totalcost;}}

            public ItemDatabase()
            {
                Item[] buying = { null, new Item(0, 9.47, 0), new Item(0, 10.97, 0), new Item(0, 19.97, 0), new Item(0, 13.28, 0), new Item(0, 5.97, 0), new Item(0, 4.99, 0), new Item(0, 4.99, 0), new Item(0, 4.99, 0) };
                this.Inventory = buying;
            }
            public Item getItemFromI(int i)
            {
                return Inventory[i];
            }
            public string BoughtToString()
            {
                _totalcost = 0;
                StringBuilder sb = new StringBuilder();
                for (int i = 1; i < 9; i++)
                {
                    switch (i)
                    {
                        case 1:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\n25ft. extention cord " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 2:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\n50ft. extention cord " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 3:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\n100ft. extention cord " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 4:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\n60 Watt LED Light Bulb(8-Pack) " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 5:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\n60-Watt Equivalent Spiral CFL Light Bulb, Soft White (4-Pack) " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 6:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\nFebreze Air Effects Hawaiian Aloha Air Freshener- 8.8oz / 2ct " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 7:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\nFebreze Air Effects Linen & Sky Scent, 8.8 oz, 2 pk " +
                                        
                                        Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        case 8:
                            {
                                if (Inventory[i].numOf > 0)
                                {
                                    sb.Append("\nFebreze Air Effects Gain Original Scent, 8.8 oz, 2 pk " + Inventory[i].numOf + "@" + Inventory[i].value + "      " + Inventory[i].totalVal);
                                    _totalcost += Inventory[i].totalVal;
                                }
                                break;
                            }
                        default:
                            break;

                    }
                }
                sb.Append("\nTotal - $" + _totalcost);
                return sb.ToString();
            }
        }
    }


