//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace ConsoleApplication1
{
    public class Receipt
    {
        private string Customer;
        private int IDnum;
        private ItemDatabase ItemsBought;
        private string dateTime;
       // public Receipt(string name, int id, Item[] b)
       // {
         //   Customer = name;
          //  IDnum = id;
         //   ItemsBought = b;
       // }
       public ItemDatabase GetIB
        {
            get
            {
                return ItemsBought;
            }
        }
        public Receipt(string name, int id)
        {
            Customer = name;
            IDnum = id;
            dateTime = Clock.CheckTime();
            ItemsBought = new ItemDatabase(); 
        }
        public string RecieptToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("\nCustomer Name: " + Customer+"\n");
            sb.Append("\nReceipt Date: " + dateTime + "\n");
            sb.Append("\nReceipt ID Number: " + IDnum + "\n");
            sb.Append(ItemsBought.BoughtToString() + "\n");
            return sb.ToString();
        }

    }
}
