//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace ConsoleApplication1
{
    public static class ReceiptDataBase
    {
        private static Receipt[] ReceiptBook =new Receipt[30];
        private static Receipt CurrentReceipt;
        private static int index =-1;
      
        public static int SetCR//Could maybe should use name
        {
            set
            {
                CurrentReceipt = ReceiptBook[value];
            }
        }
        public static Receipt getCR
        {
            get
            {
                return ReceiptBook[index];
            }

        }

        public static void OpenNewReceipt(string n)
        {
            index++;
            CurrentReceipt = new Receipt(n, index);
            ReceiptBook[index] = CurrentReceipt;
        }
        public static string CloseCR()
        {
            
            ReceiptBook[index] = CurrentReceipt;
            return CurrentReceipt.RecieptToString();
        }
    }
}

